#!/usr/bin/env python3
"""Mechanise the decidable half of PRE-FLIGHT, and say plainly which half it is NOT.

PRE-FLIGHT item 12 already has a script (`component_audit.py`) and is the only one of the
twelve that cannot be faked. Items 1-11 are self-attested ticks: the model writes twelve
checkmarks, and nothing anywhere reads them. That is the same silent-skip class the whole
checklist exists to prevent -- the checklist is just prose about prose.

SKILL.md says these are "judgment calls the render-time lint cannot measure". That is true of
some of them and NOT true of others: whether every slide carries speaker notes, whether a
`build:` docstring has matching `Build.step` calls, and whether the word "placeholder" is
sitting on a slide are all decidable by a program, and a program should decide them.

So this tool splits the twelve honestly:

  CHECKED       - decided mechanically, with evidence
  NOT CHECKABLE - a genuine judgment call; printed with what YOU must still tick

It never reports an unchecked item as clean. An item this tool cannot decide stays visibly
undecided, exactly like `component_audit.py` printing NOT CHECKED rather than reporting clean
on a deck it could not open.

  python3 scripts/preflight_check.py <deck.pptx> [--build build_x.py] [--selfread] [--static]

Exit 0 no findings · 1 findings · 2 could not run (never silently "clean").
"""
from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path

# Text that describes HOW a slide was made rather than its content. Shipping any of these is a
# real defect: a leaked build annotation reads to the audience as an unfinished deck.
META_PATTERNS = [
    r"\bplaceholder\b", r"\bTODO\b", r"\bFIXME\b", r"\bTBD\b", r"\blorem ipsum\b",
    r"\bAI[- ]generated\b", r"\bgenerated by\b", r"\bdraft\b",
    r"（?可点击编辑的原生图表）?", r"\(editable native chart\)", r"草稿", r"占位",
    r"<[a-z_]+>",                      # an unfilled <angle-bracket> template slot
    r"\{[a-z_]+\}",                    # an unformatted {format} slot printed raw
]
AS_OF = re.compile(r"as of\b|as-of\b|截至|数据截至|\bupdated\b", re.I)


def load_deck(path: Path):
    from pptx import Presentation
    return Presentation(str(path))


def slide_text(slide) -> list[str]:
    out = []
    for sh in slide.shapes:
        if sh.has_text_frame:
            for p in sh.text_frame.paragraphs:
                t = "".join(r.text for r in p.runs).strip()
                if t:
                    out.append(t)
    return out


def notes_text(slide) -> str:
    try:
        if slide.has_notes_slide:
            return (slide.notes_slide.notes_text_frame.text or "").strip()
    except Exception:
        pass
    return ""


# --------------------------------------------------------------- item checks ---
def item1_notes(prs, selfread):
    if selfread:
        return ("NOT CHECKABLE",
                "self-read deck: prose belongs ON the slides, notes are optional. "
                "Tick that the explanatory sentences are visible on-slide.")
    empty = [i for i, s in enumerate(prs.slides, 1) if not notes_text(s)]
    if empty:
        return ("FAIL", f"presented deck: slide(s) {empty} carry NO speaker notes "
                        f"(dk.speaker_notes). The spoken thread belongs there, not on the slide.")
    return ("PASS", f"all {len(prs.slides._sldIdLst)} slides carry speaker notes")


def item2_builds(prs, static):
    n = 0
    for s in prs.slides:
        xml = s._element.xml
        if "p:timing" in xml or "childTnLst" in xml:
            n += 1
    if static:
        return ("PASS", "user opted OUT of builds; deck is static by choice") if n == 0 else \
               ("FAIL", f"--static passed but {n} slide(s) carry build timing")
    if n == 0:
        # Whether builds were opted IN is a user choice this tool cannot observe. Failing on it
        # would fail every legitimately static deck whose author forgot `--static`, and a check
        # that cries wolf is a check people learn to skip.
        return ("ADVISORY", "no slide carries build timing — correct if the user opted OUT "
                            "(pass --static to say so); a defect if they opted IN")
    return ("PASS", f"{n} slide(s) carry build timing "
                    "(FULL staging per slide is a judgment call - still yours to tick)")


def item3b_build_docstrings(build_path):
    """`build:` in a slide function's docstring must have matching Build.step calls."""
    if not build_path:
        return ("NOT CHECKABLE", "no --build script given; pass it to check plan<->code correspondence")
    try:
        tree = ast.parse(Path(build_path).read_text(encoding="utf-8"))
    except Exception as e:
        return ("NOT CHECKABLE", f"could not parse {build_path}: {e}")
    bad, ok = [], 0
    for fn in [n for n in ast.walk(tree) if isinstance(n, ast.FunctionDef)]:
        doc = ast.get_docstring(fn) or ""
        if "build:" not in doc:
            continue
        steps = sum(
            1 for n in ast.walk(fn)
            if isinstance(n, ast.Call) and isinstance(n.func, ast.Attribute)
            and n.func.attr == "step"
        )
        if steps == 0:
            bad.append(fn.name)
        else:
            ok += 1
    if bad:
        return ("FAIL", f"docstring promises `build:` but the body has NO Build.step call: {bad}")
    if ok == 0:
        return ("PASS", "no slide function declares `build:` (consistent with a static deck)")
    return ("PASS", f"{ok} slide function(s) declare `build:` and each has Build.step calls")


def item4_charts_equations(prs, build_path):
    native = sum(1 for s in prs.slides for sh in s.shapes if getattr(sh, "has_chart", False))
    notes = [f"{native} editable-native chart(s)"]
    findings = []
    if build_path and Path(build_path).is_file():
        src = Path(build_path).read_text(encoding="utf-8")
        png = len(re.findall(r"\bequation_png\s*\(", src))
        nat = len(re.findall(r"\bequation_native\s*\(", src))
        notes.append(f"{nat} equation_native, {png} equation_png")
        if png and not nat:
            findings.append("only raster equation_png used - 1-D math must be equation_native "
                            "(raster is the 2-D carve only)")
        if re.search(r"designed_charts|plt\.savefig", src) and native == 0:
            notes.append("raster chart path used with no native chart - deliberate look?")
    if findings:
        return ("FAIL", "; ".join(findings) + " | " + ", ".join(notes))
    return ("PASS", ", ".join(notes))


def item7_as_of(prs):
    for s in prs.slides:
        for t in slide_text(s):
            if AS_OF.search(t):
                return ("PASS", f'deck carries an as-of marker: "{t[:60]}"')
    # Advisory by construction: a deck with no time-bound claims legitimately carries no date,
    # and nothing in the file can tell the two apart.
    return ("ADVISORY", "no 'as of' / 截至 date on any slide — required only if the deck carries "
                        "time-bound claims; confirm that yourself")


def item8_hygiene(prs):
    hits = []
    for i, s in enumerate(prs.slides, 1):
        for t in slide_text(s):
            for pat in META_PATTERNS:
                m = re.search(pat, t, re.I)
                if m:
                    hits.append(f"slide {i}: {m.group(0)!r} in {t[:52]!r}")
    if hits:
        return ("FAIL", "meta-annotation / unfilled slot leaked onto a slide -> " + " | ".join(hits[:6]))
    return ("PASS", "no placeholder / TODO / AI-generated / unfilled template slot on any slide")


def item10_fonts(prs):
    used = set()
    for s in prs.slides:
        for sh in s.shapes:
            if sh.has_text_frame:
                for p in sh.text_frame.paragraphs:
                    for r in p.runs:
                        if r.font.name:
                            used.add(r.font.name)
    if not used:
        return ("NOT CHECKABLE", "no explicit run fonts found (theme fonts only)")
    try:
        from matplotlib import font_manager
        have = {f.name for f in font_manager.fontManager.ttflist}
    except Exception:
        return ("NOT CHECKABLE", f"fonts used: {sorted(used)}; could not enumerate installed fonts")
    missing = sorted(f for f in used if f not in have)
    if missing:
        return ("FAIL", f"font(s) not installed here: {missing} - portability risk, "
                        f"flag them at hand-off (used: {sorted(used)})")
    return ("PASS", f"all {len(used)} font(s) resolve locally: {sorted(used)}")


JUDGMENT = {
    5:  ("Evidence real", "is every figure the REAL artifact, are PDF crops clean on all four "
                          "edges, are sourced photos licensed/watermark-free/aesthetically vetted, "
                          "is text over every hero legible against the pixels"),
    6:  ("Colour keyed", "is each accent taught on-slide at first use and used for one meaning; "
                         "loud motif <=3 appearances; the preset's `guard` line holds"),
    "6b": ("Register carries all pages", "does the quiet register signature reach ordinary "
                                         "interior slides, not just the bookends"),
    9:  ("Eye path & anchoring", "squint each slide - does the first look land on the named hero; "
                                 "then name the anchor edge of EVERY label"),
    11: ("Titles bound to takeaways", "is each content slide's title the plan's takeaway or a "
                                      "compression keeping subject+verb+claim - list the numbers"),
}


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("deck")
    ap.add_argument("--build", help="the deck's build_<name>.py, for plan<->code checks")
    ap.add_argument("--selfread", action="store_true")
    ap.add_argument("--static", action="store_true")
    a = ap.parse_args()

    deck = Path(a.deck)
    if not deck.is_file():
        print(f"NOT CHECKED - no such deck: {deck}", file=sys.stderr)
        return 2
    try:
        prs = load_deck(deck)
    except Exception as e:
        print(f"NOT CHECKED - could not open {deck}: {e}", file=sys.stderr)
        return 2

    checks = [
        (1,  "Speaker notes",          item1_notes(prs, a.selfread)),
        (2,  "Builds staged",          item2_builds(prs, a.static)),
        (3,  "Plan<->code (build:)",   item3b_build_docstrings(a.build)),
        (4,  "Charts / math native",   item4_charts_equations(prs, a.build)),
        (7,  "Claims dated",           item7_as_of(prs)),
        (8,  "Language & hygiene",     item8_hygiene(prs)),
        (10, "Hand-off: fonts",        item10_fonts(prs)),
    ]

    print(f"PRE-FLIGHT (mechanical subset) — {deck.name}")
    fails = 0
    for n, name, (status, detail) in checks:
        mark = {"PASS": "✓", "FAIL": "✗", "ADVISORY": "!", "NOT CHECKABLE": "—"}[status]
        if status == "FAIL":
            fails += 1
        print(f"  {mark} {n:>2}. {name:<22} {detail}")

    print("\n  ( ! = advisory: real but undecidable from the file alone — read it, do not ignore it )")
    print("\n  NOT CHECKABLE BY ANY PROGRAM — these stay YOUR ticks, and this tool")
    print("  deliberately does not imply it covered them:")
    for k, (name, what) in JUDGMENT.items():
        print(f"    ? {str(k):>2}. {name:<26} {what}")
    print("\n    12. Form diversity            -> run scripts/component_audit.py (its own gate)")
    print("     3. Plan<->code (a)(c)        -> diff the design-plan rows + cover promises by hand")

    if fails:
        print(f"\n{fails} mechanical finding(s) — not ready to render.")
        return 1
    print("\nmechanical subset clean. The five judgment items above are still unticked.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
